In [18]:
#Import des librairies
import pandas as pd
import numpy as np
import ast


In [19]:
#import de la BDD d'entrainement
df=pd.read_csv("C:/Users/hugol/Desktop/cours_ece/test/ML/reconnaissance_doc/BDD_etape2_papierid.csv",sep=";")

In [20]:
df

Labels                                               Mots
0   Carte d'identité  ['repuue', 'anse', '7oozzmio7z', 'carte', 'did...
1   Carte d'identité  ['republique', 'francaise', 'ees', 'toustou', ...
2   Carte d'identité  ['epaub', 'r', 'loue', 'ranse', 'cnoin', 'lecu...
3   Carte d'identité  ['e', 'r', 'p', 'ublis', 'u', 'fra', 'e', 'nic...
4   Carte d'identité  ['republioue', 'francase', 'cate', 'ancaleeien...
5   Carte d'identité  ['erncaees', 'e', 'luoue', 'rebue', 'eseoie', ...
6   Carte d'identité  ['rans', 'epublue', 'mzissazas', 'lues', 'vnoe...
7   Carte d'identité  ['republoue', 'franase', 'crenatoerenen', 'o1z...
8   Carte d'identité  ['ls', 'ros', 'lcas', 'ale', 'gode', 'saldlaul...
9   Carte d'identité  ['dein', 'se', 'rpuoue', 'cand', 'le', 'e', 'e...
10         Passeport                           ['evlgos', 'cce', 'col']
11         Passeport  ['republique', 'francaise', 'psotooll', 'ule',...
12         Passeport  ['rerublioue', 'fancaise', 'pssepont', 'ousoes...
13         Passeport                    ['wdais', 'ruduoul', 'tanciss']
14            Permis                                                 []
15            Permis                                                 []
16            Permis                                  ['wipges', 'coe']
17            Permis                  ['uaues', 'ain', 'tueat', 'oune']
18            Permis  ['permis', 'conduire', 'de', 'eruolous', 'ranc...
19            Permis  ['conduirt', 'permis', 'de', 'reru', 'slique',...
20            Permis  ['conduire', 'permis', 'de', 'begubliole', 'fl...
21            Permis  ['perms', 'conduire', 'de', 'blrunoul', 'eonca...
22            Permis  ['conduire', 'permis', 'de', 'berutliie', 'ean...
23            Permis  ['conduire', 'permis', 'de', 'eru', 'blloue', ...

In [21]:
#On extrait un de chaque pour la validation
valid=[df["Labels"][9],ast.literal_eval(df["Mots"][9])]
valpass=[df["Labels"][13],ast.literal_eval(df["Mots"][13])]
valperm=[df["Labels"][23],ast.literal_eval(df["Mots"][23])]
print(valid)
print(valpass)
print(valperm)

["Carte d'identité", ['dein', 'se', 'rpuoue', 'cand', 'le', 'e', 'e', 'n', 'siil', 's', 'noe']]
['Passeport', ['wdais', 'ruduoul', 'tanciss']]
['Permis', ['conduire', 'permis', 'de', 'eru', 'blloue', 'eanlael', 'richard', 'cue', 'ead', 'de', 'congi', 'caise', 'tprw', 'saod', 'suol', 'iseldtce', 'scraas', 'lloos', 'mnalbveee', 'n']]


In [22]:
#On supprime les lignes de validation
df.drop(9, inplace=True)
df.drop(13, inplace=True)
df.drop(23, inplace=True)
df.reset_index(drop=True)


Labels                                               Mots
0   Carte d'identité  ['repuue', 'anse', '7oozzmio7z', 'carte', 'did...
1   Carte d'identité  ['republique', 'francaise', 'ees', 'toustou', ...
2   Carte d'identité  ['epaub', 'r', 'loue', 'ranse', 'cnoin', 'lecu...
3   Carte d'identité  ['e', 'r', 'p', 'ublis', 'u', 'fra', 'e', 'nic...
4   Carte d'identité  ['republioue', 'francase', 'cate', 'ancaleeien...
5   Carte d'identité  ['erncaees', 'e', 'luoue', 'rebue', 'eseoie', ...
6   Carte d'identité  ['rans', 'epublue', 'mzissazas', 'lues', 'vnoe...
7   Carte d'identité  ['republoue', 'franase', 'crenatoerenen', 'o1z...
8   Carte d'identité  ['ls', 'ros', 'lcas', 'ale', 'gode', 'saldlaul...
9          Passeport                           ['evlgos', 'cce', 'col']
10         Passeport  ['republique', 'francaise', 'psotooll', 'ule',...
11         Passeport  ['rerublioue', 'fancaise', 'pssepont', 'ousoes...
12            Permis                                                 []
13            Permis                                                 []
14            Permis                                  ['wipges', 'coe']
15            Permis                  ['uaues', 'ain', 'tueat', 'oune']
16            Permis  ['permis', 'conduire', 'de', 'eruolous', 'ranc...
17            Permis  ['conduirt', 'permis', 'de', 'reru', 'slique',...
18            Permis  ['conduire', 'permis', 'de', 'begubliole', 'fl...
19            Permis  ['perms', 'conduire', 'de', 'blrunoul', 'eonca...
20            Permis  ['conduire', 'permis', 'de', 'berutliie', 'ean...

In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# Division des données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(df['Mots'], df['Labels'], test_size=0.2, random_state=42)

# Création du pipeline avec un extracteur de caractéristiques (CountVectorizer) et un modèle de classification (MultinomialNB)
model = make_pipeline(CountVectorizer(), MultinomialNB())

# Entraînement du modèle sur les données d'entraînement
model.fit(X_train, y_train)

# Prédiction sur les données de test
y_pred = model.predict(X_test)

# Évaluation du modèle
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Affichage du rapport de classification et de la matrice de confusion
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.60

Classification Report:
                  precision    recall  f1-score   support

Carte d'identité       1.00      0.33      0.50         3
       Passeport       0.00      0.00      0.00         0
          Permis       0.67      1.00      0.80         2

        accuracy                           0.60         5
       macro avg       0.56      0.44      0.43         5
    weighted avg       0.87      0.60      0.62         5


Confusion Matrix:
[[1 1 1]
 [0 0 0]
 [0 0 2]]


c:\Users\hugol\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\hugol\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\hugol\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita

##Validation

In [24]:
#Papier id
nouvelle_phrase = ' '.join(valid[1])
print(model.predict([nouvelle_phrase]))

["Carte d'identité"]


In [25]:
#Permis
nouvelle_phrase = ' '.join(valperm[1])
print(model.predict([nouvelle_phrase]))

['Permis']


In [30]:
#Passeport
nouvelle_phrase = ' '.join(valpass[1])
print(model.predict([nouvelle_phrase]))

['Permis']


In [29]:
#Export du model
import joblib

joblib.dump(model, 'model_papierid.pkl')


['model_papierid.pkl']